In [7]:
import numpy as np
import time
from numpy.random import rand

n = 150

matA = np.array(rand(n, n))
matB = np.array(rand(n, n))
matC = np.array([[0] * n for _ in range(n)]) 

start = time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            matC[i][j] = matA[i][k] * matB[k][j]
print("파이썬의 기능만으로 계산한 결과 : %.2f[sec]" % float(time.time() -start))

start = time.time()
matC - np.dot(matA, matB)

print("Numpy의 기능만으로 계산한 결과 : %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과 : 1.93[sec]
Numpy의 기능만으로 계산한 결과 : 0.00[sec]


In [10]:
import numpy as np

storages = [ 24, 3, 4, 23, 10, 12]
print(storages)

np_storages = np.array(storages)

print(type(np_storages))

[24, 3, 4, 23, 10, 12]
<class 'numpy.ndarray'>


In [16]:
storages = [ 1,2,3,4]
new_storages = []
for n in storages:
    n += n 
    new_storages.append(n)
print(new_storages)

[2, 4, 6, 8]


In [18]:
import numpy as np
storages = np.array([1,2,3,4])
storages += storages
print(storages)


[2 4 6 8]


In [19]:
arr = np.array([2,5,3,4,8])

print('arr+arr')
print(arr+arr)

print('arr-arr')
print(arr-arr)

print('arr**3')
print(arr**3)

print('1/arr')
print(1 / arr)


arr+arr
[ 4 10  6  8 16]
arr-arr
[0 0 0 0 0]
arr**3
[  8 125  27  64 512]
1/arr
[0.5        0.2        0.33333333 0.25       0.125     ]


In [23]:
import numpy as np

arr = np.arange(10)
print(arr)

print(arr[3:6])

arr[3:6] = 24

print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5]
[ 0  1  2 24 24 24  6  7  8  9]


In [26]:
arr1 = np.array([1,2,3,4,5])

print(arr1)

arr2=arr1
arr2[0]= 100
print(arr1)

arr1 = np.array([1,2,3,4,5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

print(arr1)

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[1 2 3 4 5]


In [30]:
import numpy as np
arr = np.array([2,3,4,5,6,7])

print(arr%2 == 0)

print(arr[arr %2 == 0])

[ True False  True False  True False]
[2 4 6]


In [31]:
arr = np.array([2,4,6,7])
print(arr[np.array([True,True,True,False])])

[2 4 6]


In [32]:
arr = np.array([2,4,6,7])
print(arr[arr%3==1])

[4 7]


In [34]:
import numpy as np

arr = np.array([4,-9,16,-4,20])
print(arr)

arr_abs = np.abs(arr)
print(arr_abs)

print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

[ 4 -9 16 -4 20]
[ 4  9 16  4 20]
[5.45981500e+01 8.10308393e+03 8.88611052e+06 5.45981500e+01
 4.85165195e+08]
[2.         3.         4.         2.         4.47213595]


In [41]:
import numpy as np

arr1= [2,5,7,9,5,2,]
arr2= [2,5,8,3,1]

new_arr1 = np.unique(arr1)
print(new_arr1)

print(np.union1d(new_arr1,arr2))

print(np.intersect1d(new_arr1, arr2))
print(np.setdiff1d(new_arr1,arr2))


[2 5 7 9]
[1 2 3 5 7 8 9]
[2 5]
[7 9]


In [46]:
import numpy as np
from numpy.random import randint

arr1 = randint(0,11, (5 ,2))
print(arr1)

arr2 = np.random.rand(3)
print(arr2)


[[10  6]
 [ 2  5]
 [ 4  7]
 [ 8  0]
 [ 0  0]]
[0.1608302  0.02962341 0.07163019]


In [48]:
import numpy as np

arr = np.array([[1,2,3,4,], [5,6,7,8]])
print(arr)

print(arr.shape)

print(arr.reshape(4,2))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
