In [7]:
import numpy as np
import time
from numpy.random import rand

N = 150

matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

start = time.time()

for i in range(N):
    for i in range(N):
        for k in range(N):
            matC[i][i] - matA[i][k] * matB[k][i]

print("파이썬의 기능만으로 계산한 결과 : %.2f[sec]" % float(time.time() -start))

start = time.time()

matC = np.dot(matA, matB)

print("NUMPY를 사용한 경우의 계산 결과 : %.2f[sec]" % float(time.time() -start))

파이썬의 기능만으로 계산한 결과 : 2.13[sec]
NUMPY를 사용한 경우의 계산 결과 : 0.00[sec]


In [16]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [17]:
import numpy as np

arr = np.array([[1,2,3], [4,5,12], [15,20,22]])

print(arr.sum(axis=1))

[ 6 21 57]


In [19]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])

print(arr[[3,2,0]])

[[7 8]
 [5 6]
 [1 2]]


In [21]:
import numpy as np
arr = np.arange(25).reshape(5, 5)

print(arr[[1,3,0]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


In [22]:
import numpy as np

arr = np.arange(10).reshape(2,5)

print(arr.T)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [13]:
import numpy as np

arr = np.array([[1,2,3,4], [ 5,6,7,8,]])
print(arr)

print(arr.shape)

print(arr.reshape(4,2))

arr = np.array([[1,2,3], [4,5,6]])
print(arr[1])

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[4 5 6]


In [18]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9,]])
print(arr)

print(arr[0,2])

print(arr[1:, :2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5]
 [7 8]]


In [21]:
arr = np.array([15, 30, 5])
arr.argsort()

array([2, 0, 1])

In [27]:
import numpy as np

arr = np.array([[8,4,2], [3,5,1]])

print( arr.argsort())

print(np.sort(arr))

arr.sort(1)
print(arr)

[[2 1 0]
 [2 0 1]]
[[2 4 8]
 [1 3 5]]
[[2 4 8]
 [1 3 5]]


In [2]:
import numpy as np

arr = np.arange(9).reshape(3,3)

print(np.dot(arr, arr))

vec = arr.reshape(9)

print(np.linalg.norm(vec))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
14.2828568570857


In [23]:
x = np.arange(6).reshape(2, 3)
print(x + 1)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
arr = np.arange(15).reshape(3,5)

print(arr.mean(axis=0))
print(arr.mean(axis=1))

print(arr.min())
print(arr.argmax(axis=0))



[5. 6. 7. 8. 9.]
[ 2.  7. 12.]
0
[2 2 2 2 2]


In [24]:
import numpy as np

x = np.arange(15).reshape(3,5)
print("x:")
print(x)

x:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
y = np.array([np.arange(5)])
print("y")
print(y)

y
[[0 1 2 3 4]]


In [26]:
z= x - y
print("z")
print(z)

z
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
